services:
  postgres:
    image: postgres:14-alpine
    container_name: nurgling_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nurgling_db
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Монтирование SQL-скрипта
    networks:
      - postgres

volumes:
  postgres_data:

networks:
  postgres:
    driver: bridge